name: ci
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      -
        name: Export Github Auth Token
        run: echo "GH_AUTH_TOKEN=${{ secrets.GH_AUTH_TOKEN }}" >> $GITHUB_ENV
      -
        name: Run go tests
        run : cd src/; go test .
      -
        name: Set TAG env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DH_USERNAME }}/stargazers-cmc:${{ env.TAG }},${{ secrets.DH_USERNAME }}/stargazers-cmc:latest
